#!/usr/bin/bash

set -x #echo on

if (($# != 1))
then
  echo "Usage: stop_cluster <base_port>"
  exit 1
fi

base_port=$1

for i in 0 1 2 3 4 5
do
 p=$((base_port + i))
 cd $p 
 pid=`cat pid`
 kill $pid
 rm pid
 cd -
done
